sudo: required
services:
- docker
env:
  global:
  - VERSIONS="2.7,3.3,3.4,3.5"
  - secure: AAddutsizMlfzkkLjHWs3O+R1Z4aDiK4WXWn99mLkWbCUXQTC+SJf+ZUPQIZRBAp/tW6wa1Vi+1yYvL/79DHXb5UeMFDwzYxUu4hx9omHcRvXRt0RJ8X71iYl9fIyLzScvxgriYWMuUizVajSSXNAR05zdopqwz7k0/s2FCkxkkBDoTMuyeQ1DeYKMooI4R2C+88wpsKrwHlXmFu5QokTPGLBzeSFbDJfECNllGZd82lYE0QXvYjJfVAVk2NdabMBowuUXRq8smVD6FgogzrQjmnxmdgHX8unoivUDTuaOS5X4jA2lxZu1zMfTHPDQSBMaFMG8Mue96MQCghsLdo11tnwebB4GzUGYMpEuLwwhbCBg+LZIKGc1YuwmDeeusrp64RmSe6NvD2uze72KtbGXNYwbYGpq7mdTEMfrtI+Ke3GH07JfUqsJQP/Pbs46+nfhwGQGr9YVecDtYoEp0jaTgS7zK0fswa30HiP1TZKC4UMse2WwOo85/a+hf6m7Zxb1aovMxk0FNZYAH6czS6nkv0SlfxGq40TmRpit3PLdBA356TSVhXs8GMYITaqyybdYiZC7OWqy4BbRBEfdOq3AOYaTz1t0xBZyBbiQWWt3IpAbc8vWNoOHNFBjtAQ0TlRWaCE97tot0p/zVikqp9mc72GeAl6QJbT3BTXV9HhnQ=
script:
- ". test/run"
notifications:
  slack:
    secure: EFUvMVPi5xqDIhpez42YqgU1fvweWAIdy5XXSnVj1JwsqvMxzVRS9jZTW7bRB8Ylf5yNRUkdUFG4qJaZrrP9Hp3njtfyWT7+q71F5QRiQIV5Oin8TXmx1qK5zfBgZgCqJxVlRqwwTvHsDtC4A0AqhOZH0474fXfV7ZmzYu1roevbmOXf6IdKhaFVUGinRzP0kLHXWVKKKaAjjhHp4VX2RDTUKHMnTxuM2nN4OMrWp6pmrkxvzXx8gZcR29UMcl95SVd3o5aHwb8NX0CvN3jQcKQZeYdfQ+AcQ89MMyeKgXafejLu6I3/7pNXDrLasRjp3MAiUjhxHsHhtvsZJBRu+D732XQatQKVAEeSJ8CzYNie4tPnVb6yvhxVLO3F28tzc3U04+Iam726qYi2IXflHPbjJranjMHbh9iFDn/cN9i6n+vC7BGYB3sX5sP9lcNsurERO6GtGeWaImlkzS82rYfSJyQ1+qghPtfZ0CB0byDLbKliOcdLydqIfO4aWVOAl437yQuPY3qmBdFSymPGm/54hvZ1vV5PhvbPt7WAWla3y6AeVfuqivREurCOgjEGQhYz/7qUNF3bAL8BKZ1QZxFKDNIQZuOyyUCvz4+32MlrRdPx+fucQiwE8c3lJ0a9tbJ8+oXlgTVl+ArxJxrnEcF/YgQKimkSWIQPOEvr4bc=
